CREATE TABLE player (
 id BIGINT  NOT NULL PRIMARY KEY,
 CONSTRAINT pk_player FOREIGN KEY (id) REFERENCES client (id)
);

CREATE TABLE game (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  game_type INTEGER,
  CONSTRAINT pk_game PRIMARY KEY (id)
);

CREATE TABLE favorites (
  player_id BIGINT NOT NULL,
   game_id BIGINT NOT NULL,
   foreign key (player_id) references player (id)
           on update cascade,
   foreign key (game_id) references game (id)
              on update cascade,
   UNIQUE (player_id, game_id)
);

CREATE TABLE notification (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   message VARCHAR(255),
   arrival TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_notification PRIMARY KEY (id)
);

CREATE TABLE player_notifications (
  buyer_id INTEGER NOT NULL,
   notification_id BIGINT NOT NULL,
   foreign key (buyer_id) references player (id)
              on update cascade,
      foreign key (notification_id) references notification (id)
                 on update cascade,
      UNIQUE (buyer_id, notification_id)
);

ALTER TABLE player ADD CONSTRAINT fk_player_on_client FOREIGN KEY (id) REFERENCES client (id);
CREATE SEQUENCE public.client_seq;
